---
title: OneNote
url: http://onenote.work
timezone: America/Los_Angeles
collections:
  posts:
    title: Components
    output: true
    Components:
    - hero
    - hero-full
    - section
  uploads:
    title: Uploads
    output: true
  enus:
    title: enus-homepage-items
    output: true
  iphone:
    title: iPhone
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
destination: "./_site"
exclude:
- Gem*
- Guard*
- "*.rb"
- ".sass-cache"
- ".git*"
- config.rb
